### ISSUE TITLE
lightgbm

### ISSUE THREAD

**Issue by lavishpruthi** [ShubhankarRawat/Heart-Disease-Prediction#2]
In jupyter notebook it first installs the lightgbm them u can import. It shows error if not installed. must include in code so that no  issues are created.
Add ***!pip install lightgbm*** in the code

**Comment by ShubhankarRawat** [comment]
Thanks for the comment. However, I have written my code in Spyder (script and not notebook), therefore I have the libraries pre-installed in my env
